---
- name: Enable sddm
  service:
    name: sddm
    enabled: true
    masked: no

- name: Enable NetworkManager
  service:
    name: NetworkManager
    enabled: true
    masked: no
- name: Create User Directories
  command: xdg-user-dirs-update
  become: True
  become_user: "{{ username }}"

- name: Create kitty config directory
  command: mkdir -p /home/{{ username}}/.config/kitty
  become: True
  become_user: "{{ username }}"

- name: Copy kitty dot file
  command: cp /tmp/{{ dotfiles.destination}}/kitty/kitty.conf /home/{{ username}}/.config/kitty/kitty.conf
  become: True
  become_user: "{{ username }}"

- name: Copy zshenv
  command: cp /tmp/{{ dotfiles.destination}}/.zshenv /home/{{ username}}/.zshenv
  become: True
  become_user: "{{ username }}"

- name: Create zsh config directory
  command: mkdir -p /home/{{ username}}/.config/zsh
  become: True
  become_user: "{{ username }}"

- name: Copy zshrc
  command: cp /tmp/{{ dotfiles.destination}}/zsh/.zshrc /home/{{ username}}/.config/zsh/.zshrc
  become: True
  become_user: "{{ username }}"

- name: Copy aliases
  command: cp /tmp/{{ dotfiles.destination}}/zsh/aliases /home/{{ username}}/.config/zsh/aliases
  become: True
  become_user: "{{ username }}"

- name: Copy default wall paper
  command: cp /tmp/{{ dotfiles.destination}}/1.jpg /home/{{ username}}/1.jpg
  become: True
  become_user: "{{ username }}"

- name: Copy cinnamon settings
  command: cp /tmp/{{ dotfiles.destination}}/dconf.dump /home/{{ username}}/dconf.dump
  become: True
  become_user: "{{ username }}"

- name: Restore cinnamon settings
  shell:
    cmd: dconf load / < /home/{{ username}}/dconf.dump
  become: True
  become_user: "{{ username }}"

- name: Install theme files
  command: curl -L {{themefiles.url}} -o /tmp/{{themefiles.destination}}/Dracula.zip && unzip /tmp/{{themefiles.destination}}/Dracula.zip -d /tmp/{{themefiles.destination}}/Dracula && mkdir /home/{{username}}/.themes/Dracula && mv {{themefiles.destination}}/Dracula/gtk-master/* /home/{{username}}/.themes/Dracula
  become: True
  become_user: "{{ username }}"

- name: Install icon files
  command: curl -L {{iconfiles.url}} -o /tmp/{{iconfiles.destination}}/Dracula.zip && unzip /tmp/{{iconfiles.destination}}/Dracula.zip -d /tmp/{{iconfiles.destination}} && mv /tmp/{{iconfiles.destination}}/Dracula /home/{{username}}/.icons/
  become: True
  become_user: "{{ username }}"