---
- name: Enable sddm
  service:
    name: sddm
    enabled: true
    masked: no

- name: Enable NetworkManager
  service:
    name: NetworkManager
    enabled: true
    masked: no

- name: Copy kitty dot files
  command: mkdir -p /home/{{ username}}/.config/kitty && cp /tmp/{{ dotfiles.destination}}/kitty/kitty.conf /home/{{ username}}/.config/kitty/kitty.conf
  become: True
  become_user: "{{ username }}"
