---
- name: Enable sddm
  service:
    name: sddm
    enabled: true
    masked: no

- name: Enable NetworkManager
  service:
    name: NetworkManager
    enabled: true
    masked: no

- name: Create kitty config directory
  command: mkdir -p /home/{{ username}}/.config/kitty
  become: True
  become_user: "{{ username }}"

- name: Copy kitty dot file
  command: cp /tmp/{{ dotfiles.destination}}/kitty/kitty.conf /home/{{ username}}/.config/kitty/kitty.conf
  become: True
  become_user: "{{ username }}"

- name: Copy zshenv
  command: cp /tmp/{{ dotfiles.destination}}/.zshenv /home/{{ username}}/.zshenv
  become: True
  become_user: "{{ username }}"

- name: Create zsh config directory
  command: mkdir -p /home/{{ username}}/.config/zsh
  become: True
  become_user: "{{ username }}"

- name: Copy zshrc
  command: cp /tmp/{{ dotfiles.destination}}/zsh/.zshrc /home/{{ username}}/.config/zsh/.zshrc
  become: True
  become_user: "{{ username }}"

- name: Copy aliases
  command: cp /tmp/{{ dotfiles.destination}}/zsh/aliases /home/{{ username}}/.config/zsh/aliases
  become: True
  become_user: "{{ username }}"

- name: Create User Directories
  command: xdg-user-dirs-update
  become: True
  become_user: "{{ username }}"