- name: Create AUR directory
  file: path=/home/{{ username }}/{{ aur.dir }}
        state=directory
        owner={{ username }}
        group={{ username }}

- name: Install AUR base packages
  aur:
    name: "{{ aur.packages }}"
    path: /tmp/
    user: "{{ username }}"
    skip_pgp: yes
