- name: install basic utils, shells, apps
  community.general.pacman:
   name:
    - tmux
    - tree
    - base-devel
    - neovim
    - kitty
    - code
    - exa
    - xdg-user-dirs
   state: present
  notify:
   - Create User Directories

- name: Install archival utils
  pacman:
    name:
      - atool
      - p7zip
      - unrar
      - unzip
      - xz
      - zip
      - bzip2
      - gzip
      - tar
      - exa
    state: present

- name: Install download utils
  pacman:
    name:
      - curl
      - wget
    state: present

- name: Install ImageMagick
  pacman:
    name: imagemagick
    state: present

- name: Install Font Cascadia code
  pacman:
    name: ttf-cascadia-code
    state: present