- name: install basic utils, shells, apps
  community.general.pacman:
   name:
    - cinnamon
    - firefox
    - sddm
    - nemo-fileroller
    - tmux
    - tree
    - base-devel
    - neovim
    - kitty
    - code
    - exa
    - xdg-user-dirs
    - bpytop
    - evince
    - exa
    - xclip
    - rofi
    - blueberry
    - timeshift
    - atool
    - p7zip
    - unrar
    - unzip
    - xz
    - zip
    - bzip2
    - gzip
    - tar
    - curl
    - wget
    - imagemagick
    - flameshot
    - obsidian
    - jdk-openjdk
    - flatpak
    - ttf-cascadia-code
    - ttf-ubuntu-font-family
   state: present

- name: Create User Directories
  command: xdg-user-dirs-update
  become: True
  become_user: "{{ username }}" 
