- name: Clone user dot files
  git: repo={{ dotfiles.url }} dest=/tmp/{{ dotfiles.destination }} accept_hostkey=yes update=no
  become: True
  become_user: "{{ username }}"
  notify:
   - Enable NetworkManager
   - Enable sddm
   - Create kitty config directory
   - Copy kitty dot file
   - Copy zshenv
   - Create zsh config directory
   - Copy zshrc
   - Copy aliases