- name: Clone user dot files
  git: repo={{ dotfiles.url }} dest=/tmp/{{ dotfiles.destination }} accept_hostkey=yes update=no
  become: True
  become_user: "{{ username }}"

- name: Create kitty config directory
  command: mkdir -p /home/{{ username}}/.config/kitty
  become: True
  become_user: "{{ username }}"

- name: Copy kitty dot file
  command: cp /tmp/{{dotfiles.destination}}/kitty/kitty.conf /home/{{username}}/.config/kitty/kitty.conf
  become: True
  become_user: "{{ username }}"

- name: Copy kitty diff file
  command: cp /tmp/{{dotfiles.destination}}/kitty/diff.conf /home/{{username}}/.config/kitty/diff.conf
  become: True
  become_user: "{{ username }}"

- name: Copy zshenv
  command: cp /tmp/{{dotfiles.destination}}/.zshenv /home/{{username}}/.zshenv
  become: True
  become_user: "{{ username }}"

- name: Create zsh config directory
  command: mkdir -p /home/{{ username}}/.config/zsh
  become: True
  become_user: "{{ username }}"

- name: Copy zshrc
  command: cp /tmp/{{ dotfiles.destination}}/zsh/.zshrc /home/{{username}}/.config/zsh/.zshrc
  become: True
  become_user: "{{ username }}"

- name: Copy powerlevel10k
  command: cp /tmp/{{ dotfiles.destination}}/zsh/.p10k.zsh /home/{{username}}/.config/zsh/.p10k.zsh
  become: True
  become_user: "{{ username }}"

- name: Copy aliases
  command: cp /tmp/{{ dotfiles.destination}}/zsh/aliases /home/{{username}}/.config/zsh/aliases
  become: True
  become_user: "{{ username }}"

- name: Create neovim directory 
  command: mkdir -p /home/{{ username}}/.config/nvim
  become: True
  become_user: "{{ username }}"

- name: Copy neovim config
  command: cp /tmp/{{ dotfiles.destination}}/nvim/init.vim /home/{{username}}/.config/nvim/init.vim
  become: True
  become_user: "{{ username }}"

- name: Create rofi directory 
  command: mkdir -p /home/{{ username}}/.config/rofi
  become: True
  become_user: "{{ username }}"

- name: Copy rofi config
  command: cp /tmp/{{ dotfiles.destination}}/rofi/config.rasi /home/{{username}}/.config/rofi/config.rasi
  become: True
  become_user: "{{ username }}"



