- name: Clone user dot files
  git: repo={{ dotfiles.url }} dest=/tmp/{{ dotfiles.destination }} accept_hostkey=yes update=no
  become: True
  become_user: "{{ username }}"
  notify:
   - Copy kitty dotfiles
   - Enable NetworkManager 