- name: Enable sddm
  service:
    name: sddm
    enabled: true
    masked: no

- name: Enable NetworkManager
  service:
    name: NetworkManager
    enabled: true
    masked: no

- name: Copy default wall paper
  command: cp /tmp/{{ dotfiles.destination}}/1.jpg /home/{{username}}/1.jpg
  become: True
  become_user: "{{ username }}"

- name: Copy cinnamon settings
  command: cp /tmp/{{ dotfiles.destination}}/dconf.dump /home/{{username}}/dconf.dump
  become: True
  become_user: "{{ username }}"

- name: Restore cinnamon settings
  shell:
    cmd: dconf load / < /home/{{username}}/dconf.dump
  become: True
  become_user: "{{ username }}"