- name: check updates
  pacman: 
   update_cache: yes
   upgrade: yes

# Configure pacman (colorize and repos)
- include: pacman.yml

# Basic apps (vlc, kitty, etc.)
- include: core-apps.yml

# Install and configure zsh
- include: zsh.yml
  when: setup_zsh == True

# Install KDE and Additional Plasma Applications
- include: cinnamon.yml
  when: install_cinnamon == True

# Web Browser
- include: "firefox.yml"
  when: install_browser == True

# AUR apps
- include: aur.yml
  when: use_aur == True

# theme and icons
- include: theme.yml
  when: pull_themefiles == True

- include: icons.yml
  when: pull_themefiles == True

# Dotfiles
- include: dotfiles.yml
  when: pull_dotfiles == True
