---

- name: install zsh
  community.general.pacman:
   name: 
    - zsh
    - zsh-completions
    - zsh-syntax-highlighting
   state: present

- name: install fzf for zsh
  community.general.pacman:
   name: 
    - fzf
   state: present


- name: change "{{ username }}"'s shell to zsh
  become: true
  user:
   name: "{{ username }}"
   shell: /usr/bin/zsh


