### Playbook Configuration Variables
# You may modify the following variables to customize the playbook to your
# specific needs, however do not remove any variables, they are all required
# for the playbook to function.

## User info
username: manu

## Task Configuration
setup_zsh: True

## Dotfiles
## Please make sure to update 
pull_dotfiles: True

dotfiles:
    url: https://github.com/linuxpiper/dotfiles.git
    destination: projects/dotfiles
    rcup_flags: -fx README.md

## Desktop
install_cinnamon: True

## App Preferences
## ===========================
# Web Browser
install_browser: True

## AUR vars
## ===========================
use_aur: True

aur:
    dir: aur
    packages:
        - yay
## ===========================
